package ass03;


/**
* ass03/randCharServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from demo.idl
* Saturday, October 22, 2016 6:57:24 PM AEDT
*/

public interface randCharServer extends randCharServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface randCharServer
