package ass03;


/**
* ass03/randCharServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from demo.idl
* Sunday, October 23, 2016 4:25:04 PM AEDT
*/

public interface randCharServer extends randCharServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface randCharServer
