package ass03;

/**
* ass03/randCharServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from demo.idl
* Sunday, October 23, 2016 4:25:04 PM AEDT
*/

public final class randCharServerHolder implements org.omg.CORBA.portable.Streamable
{
  public ass03.randCharServer value = null;

  public randCharServerHolder ()
  {
  }

  public randCharServerHolder (ass03.randCharServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ass03.randCharServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ass03.randCharServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ass03.randCharServerHelper.type ();
  }

}
