package ass03;


/**
* ass03/randCharServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from demo.idl
* Sunday, October 23, 2016 4:25:17 PM AEDT
*/

public interface randCharServerOperations 
{
  char getChar ();
  void shutdown ();
} // interface randCharServerOperations
