package ass03;


/**
* ass03/randCharServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from demo.idl
* Saturday, October 22, 2016 4:21:47 PM AEDT
*/

public abstract class randCharServerPOA extends org.omg.PortableServer.Servant
 implements ass03.randCharServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("get", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ass03/randCharServer/get
       {
         char $result = (char)0;
         $result = this.get ();
         out = $rh.createReply();
         out.write_char ($result);
         break;
       }

       case 1:  // ass03/randCharServer/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ass03/randCharServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public randCharServer _this() 
  {
    return randCharServerHelper.narrow(
    super._this_object());
  }

  public randCharServer _this(org.omg.CORBA.ORB orb) 
  {
    return randCharServerHelper.narrow(
    super._this_object(orb));
  }


} // class randCharServerPOA
