package ass03;


/**
* ass03/randCharServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from demo.idl
* Saturday, October 22, 2016 4:22:10 PM AEDT
*/

public interface randCharServerOperations 
{
  char get ();
  void shutdown ();
} // interface randCharServerOperations
